---
detectors:
  Attribute:
    enabled: false
  BooleanParameter:
    enabled: false
  ClassVariable:
    enabled: false
  DuplicateMethodCall:
    enabled: false
  FeatureEnvy:
    enabled: false
  IrresponsibleModule:
    enabled: false
  InstanceVariableAssumption:
    enabled: false
  LongParameterList:
    enabled: false
  ManualDispatch:
    enabled: false
  NestedIterators:
    max_allowed_nesting: 2
  NilCheck:
    enabled: false
  TooManyInstanceVariables:
    enabled: false
  TooManyMethods:
    enabled: false
  TooManyStatements:
    max_statements: 10
    exclude:
      - 'ActiveReport::Base#metamorph'
      - 'ActiveReport::Hash#import'
      - 'ActiveReport::Record#export'
      - 'ActiveReport::Record#import'
  UncommunicativeMethodName:
    exclude:
      - 'ActiveReport::Base#encode_to_utf8'
  UncommunicativeVariableName:
    exclude:
      - 'ActiveReport::Hash#import'
  UtilityFunction:
    enabled: false
